services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/golf_club
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - golf-network

  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=golf_club
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - golf-network

volumes:
  mysql-data:

networks:
  golf-network:
    driver: bridge
